### PR TITLE
Update Knex to v2.4.2 & Run npm audit

### PR DESCRIPTION
**Pull request by kellnerd**
This took me a bit longer than expected as I also wanted to run Bookshelf's tests suite before pushing these changes, which required setting up test databases (PostgreSQL, MySQL, SQLite). Simply following [the instructions for Docker](https://github.com/bookbrainz/bookshelf/blob/master/.github/CONTRIBUTING.md#using-docker-containers) was not enough because the containers did not allow me to use the default credentials, so I had to figure out how to change them via an additional configuration file.

I performed this update in two steps: First I tested the existing commits for the update to v1, then I updated to v2 and ran the test suite again, which required me to exchange the `sqlite3` package again (see 5ece77d7bfbccdbb902c8be050d7b37fb6e6c554).
Finally I performed an `npm audit` to update a few other dependencies with security issues.

Opening this as a draft to make it easier to review and discuss whether we want to push these changes to `master` or keep them in a feature branch and whether we want to tag a new version.
Bumping the version to 1.3.0 is not required, the alternatives are to use the git commit hash or default to the latest commit in [bookbrainz-data-js/package.json](https://github.com/metabrainz/bookbrainz-data-js/blob/d8e900740421249e44d26755be3e15cc4129301b/package.json#L69).
~I don't think it's necessary to pin a specific version/commit since~ we don't intend to do any breaking changes in this repository and the exact version will already be tracked by [yarn.lock](https://github.com/metabrainz/bookbrainz-data-js/blob/d8e900740421249e44d26755be3e15cc4129301b/yarn.lock#L1359).
Scratch that, maybe it's better to specify the exact version, otherwise yarn does not seem to pull the latest version and keeps installing an older, cached commit. I've just noticed that after I'd unlinked my local folder to use the GH package again.

P.S. Oops, at first I had accidentally opened this PR against the bookshelf repo... probably because the name was too similar :see_no_evil:

### CODE REVIEW

**Comment by yvanzo** [comment]
Great job at updating dependencies!

It’s nice to open a pull request to the main repository too, maybe after this one is ready. :banana:

**Review by MonkeyDo — APPROVED** [review]
Great, thanks for opening the PR.

~~I would indeed also encourage you to open a PR on the main repository, even though it seems like PRs are a bit dusty there.
It might prove to be useful to someone else looking to buy some time before switching libraries.~~
I forgot there was already a PR for 2.4.1 (https://github.com/bookshelf/bookshelf/pull/2120)
Not sure if we're bringing a lot more to the table but you're still welcome to open a PR if you think it could be useful to someone.

**Comment by MonkeyDo** [comment]
I think perhaps in the idle hope that more development will happen in the main repo, we should keep our changes in a feature branch (which should make it easier to rebase), in which case I would suggest renaming the branch to `update-knex-2.4` for clarity, and closing the PR.
Thanks for already having created the tag!

**Comment by kellnerd** [comment]
Agreed, I have renamed the branch according to your suggestion. Since we are referring to the tagged commit, it doesn't matter how the branch is named or whether this PR is merged.

> I forgot there was already a PR for 2.4.1 (https://github.com/bookshelf/bookshelf/pull/2120)

That PR only updates to Knex 1.0.3 and contains exactly the first three commits from our branch, so it would make sense to open a PR (again) for my subsequent commits. Whether that gets merged is another question.

**Comment by kellnerd** [comment]
Upstream PR is now open at https://github.com/bookshelf/bookshelf/pull/2125.
I've created a separate branch for that PR which does not include the last commit with which I've bumped our local bookshelf version to 1.3.0.

**Pull request closed without merging**
